# Generated by Django 4.0.3 on 2022-03-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_rename_img_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='images',
        ),
    ]
